baseURL: "/"
languageCode: en
DefaultContentLanguage: en
title: Website of Jane Doe
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
googleAnalytics: "UA-195471994-1"
params:
  contactFormAction: "https://formspree.io/f/xayaqyre"
